### ISSUE TITLE
La documentación debe escribirse a ser posible en el formato final

### ISSUE THREAD

**Issue by JJ** [harvestcore/tfm-doc#4]
En este caso, por ejemplo, está incompleta y en markdown. Si no está completa, no se puede cerrar el milestone uno, que incluye esta parte de la documentación 
https://github.com/harvestcore/tfm-doc/blob/9dfc0dd45b248e864119a821dac106a895fa2570/md/analisis/herramientas.md?plain=1#L15
Es más conveniente que empieces ya a escribir la memoria, e incluyas todo lo básico, y en CI la comprobación de compilación y ortográfica de la misma.

**Comment by harvestcore** [comment]
He agregado el esqueleto del proyecto en Latex, además de CI para construir el PDF y también para comprobar la ortografía. Si te parece bien puedo mezclar este progreso y en otras tareas ir pasando el contenido que tengo en Markdown a Latex (como por ejemplo en harvestcore/matroos#38, harvestcore/matroos#37 o harvestcore/matroos#36)

@JJ

**Comment by JJ** [comment]
¿Alguna razón por la que quieras tener dos repos independientes?

**Comment by harvestcore** [comment]
@JJ, Principalmente para no mezclar el software con documentación del TFM, y para no mezclar idiomas, el software está todo en inglés y este está en español.

El repo de software obviamente va a tener documentación, pero solo referente al software. Mientras que este repo va a tener contenido del TFM. Además, tras terminar el TFM me gustaría seguir desarrollando características del software, ya que tengo un montón de ideas, y me gustaría que fuera independiente del TFM (aunque quizá con un fork o una copia del repo serviría)

**Comment by JJ** [comment]
El problema es que los hitos tendrán que avanzarse con la documentación y el código a la vez. La documentación no es un proyecto aparte, es parte del proyecto. En cualquier proyecto suele haber directorios `doc` para la documentación, que además puedes publicar en la web si quieres.

**Comment by harvestcore** [comment]
Roger that. Tiene sentido. Si te parece mezclo esto para que no se quede pendiente y el paso al otro repo lo hago cerrando la issue harvestcore/tfm-doc#6.
